[workspace]
resolve = "2"
members = [
    "crates/scream-core",
    "crates/scream-cli",
    "crates/scream-ffi",
    "crates/scream-python",
]

[profile.release]
opt-level = 3
lto = true
strip = true
