[package]
name = "scream-ffi"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[lib]
name = "scream"
crate-type = ["cdylib", "staticlib"]

[dependencies]
screampp = { path = "../scream-core" }
