# =============================================================================
# SCREAM++ Complete Configuration File Template
# =============================================================================
#
# This file contains ALL available settings for a `scream place` run.
# - To use a setting, uncomment it and modify its value.
# - Settings that are commented out will use the application's default value,
#   which is shown in the comment for reference.
# - For detailed explanations, please refer to the full user manual.

# -----------------------------------------------------------------------------
# [forcefield] - Energy function and forcefield parameters
# -----------------------------------------------------------------------------
[forcefield]

# s-factor for the flat-bottom potential. This is a critical parameter for accuracy.
# Its optimal value is dependent on the diversity of the chosen rotamer library.
# Default: 1.1 (optimized for rmsd-1.0 libraries)
s-factor = 1.1

# Path or logical name for the main forcefield parameter file.
# Logical names: 'exp-6@0.4', 'lj-12-6@0.4', etc.
# Default: "exp-6@0.4"
# forcefield-path = "exp-6@0.4"

# Path or logical name for the flat-bottom delta parameter file.
# The diversity (e.g., "rmsd-1.0") should match the rotamer library.
# Default: "rmsd-1.0"
# delta-params-path = "rmsd-1.0"

# [Optional] Rules for applying custom weights to energy components between
# different types of atoms (Atom Roles: Backbone, Sidechain, Ligand, Water, Other).
# By default, all interactions have a weight of 1.0.
# [[forcefield.energy-weights.rules]]
# groups = ["Backbone", "Sidechain"]
# weights = { vdw = 1.0, coulomb = 1.0, hbond = 1.0 }

# -----------------------------------------------------------------------------
# [sampling] - Side-chain conformation sampling
# -----------------------------------------------------------------------------
[sampling]

# Path or logical name for the rotamer library.
# The diversity (e.g., "rmsd-1.0") should match `delta-params-path`.
# Logical names: 'charmm@rmsd-1.0', 'amber@rmsd-1.0', etc.
# Default: "charmm@rmsd-1.0"
# rotamer-library = "charmm@rmsd-1.0"

# -----------------------------------------------------------------------------
# [optimization] - Algorithm control
# -----------------------------------------------------------------------------
[optimization]

# The number of lowest-energy, unique solutions to generate and save.
# Default: 1
num-solutions = 1

# Maximum number of iterations for the main clash resolution algorithm.
# Default: 100
# max-iterations = 100

# Whether to include the input structure's original side-chain conformation as
# a candidate solution during the optimization.
# Default: true
# include-input-conformation = true

# Number of refinement iterations (singlet optimization) to run after the
# main loop converges. Set to 0 to disable.
# Default: 2
# final-refinement-iterations = 2

# [optimization.convergence]
# --- Convergence Criteria ---
# The algorithm is considered converged if the best energy improves by less than
# this threshold over a 'patience' number of iterations.
# Default: 0.01 (kcal/mol)
# energy-threshold = 0.01

# The number of consecutive iterations with insufficient energy improvement
# before the optimization loop terminates.
# Default: 5
# patience-iterations = 5

# [optimization.simulated-annealing]
# --- [Optional] Simulated Annealing ---
# To enable, uncomment this entire section. This can help the algorithm escape
# local energy minima but will increase runtime.
# initial-temperature = 5.0
# final-temperature = 0.1
# cooling-rate = 0.9
# steps-per-temperature = 100

# -----------------------------------------------------------------------------
# [residues-to-optimize] - Defines which residues to modify
# -----------------------------------------------------------------------------
[residues-to-optimize]

# Choose ONE of the following types: "all", "list", or "ligand-binding-site".

# TYPE 1: Optimize all residues.
# This is the default if the section is omitted.
type = "all"

# TYPE 2: Optimize a specific list of residues.
# `include` specifies which residues to target. If `include` is empty, it defaults to all residues.
# `exclude` specifies which residues to ignore, even if they are in the `include` selection.
# type = "list"
# include = [
#   { chain-id = 'A', residue-number = 25 },
#   { chain-id = 'A', residue-number = 101 },
# ]
# exclude = []

# TYPE 3: Optimize residues within a certain radius of a ligand.
# The radius is measured from any heavy atom of the ligand to any heavy atom of a protein residue.
# type = "ligand-binding-site"
# radius-angstroms = 5.0
# [residues-to-optimize.ligand-residue]
# chain-id = 'X'
# residue-number = 999

# -----------------------------------------------------------------------------
# Global Settings
# -----------------------------------------------------------------------------

# Path or logical name for the residue topology registry.
# In most cases, the default is sufficient.
# Default: "default"
# topology-registry-path = "default"
