[package]
name = "screampp"
description = "A modernized, high-performance library for protein side-chain placement based on the SCREAM method."
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
nalgebra = "0.33.2"
thiserror = "2.0.12"
