name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests (core)
        run: cargo test -p screampp --verbose

      - name: Run tests (cli)
        run: cargo test -p scream-cli --verbose
